/**
 * Curated lists of real gazetted suburbs per Australian capital city.
 * Sourced from ABS suburb/locality boundaries and OSM administrative data.
 * Spread across inner, middle, and outer rings to ensure variety.
 */
export const SUBURBS_BY_CITY: Record<string, string[]> = {
  Sydney: [
    "Abbotsbury", "Abbotsford", "Alexandria", "Allambie Heights", "Annandale",
    "Annangrove", "Arncliffe", "Artarmon", "Ashbury", "Ashfield",
    "Asquith", "Auburn", "Avalon Beach", "Balgowlah", "Balmain",
    "Bangor", "Bankstown", "Banksia", "Barangaroo", "Barden Ridge", "Bass Hill", "Baulkham Hills", "Bayview", "Beacon Hill",
    "Beaconsfield", "Beaumont Hills", "Beecroft", "Belfield", "Bellevue Hill",
    "Belmore", "Berala", "Berowra", "Beverly Hills", "Bexley",
    "Birrong", "Blacktown", "Blakehurst", "Bondi", "Bondi Beach",
    "Bondi Junction", "Botany", "Brighton-Le-Sands", "Bronte", "Brookvale",
    "Burwood", "Cabarita", "Cabramatta", "Cammeray", "Camperdown",
    "Campsie", "Canley Heights", "Canley Vale", "Canterbury", "Caringbah",
    "Carlingford", "Carlton", "Castle Hill", "Castlecrag", "Centennial Park",
    "Chatswood", "Cherrybrook", "Chester Hill", "Chifley", "Chippendale",
    "Clontarf", "Clovelly", "Collaroy", "Concord", "Coogee",
    "Cremorne", "Crows Nest", "Croydon", "Curl Curl", "Daceyville",
    "Darling Point", "Darlinghurst", "Davidson", "Dawes Point", "Dee Why",
    "Double Bay", "Dover Heights", "Drummoyne", "Dulwich Hill", "Dundas",
    "East Hills", "Eastgardens", "Eastwood", "Edgecliff", "Elanora Heights",
    "Elizabeth Bay", "Emu Plains", "Engadine", "Enmore", "Epping",
    "Erskineville", "Eveleigh", "Fairfield", "Fairlight", "Forest Lodge",
    "Gladesville", "Glebe", "Glenmore Park", "Gordon", "Granville",
    "Greenacre", "Greenwich", "Guildford", "Gymea", "Haberfield",
    "Harris Park", "Haymarket", "Heathcote", "Homebush", "Homebush West",
    "Hornsby", "Hunters Hill", "Hurlstone Park", "Hurstville", "Ingleside",
    "Jannali", "Kellyville", "Kellyville Ridge", "Kensington", "Killara",
    "Kingsford", "Kingsgrove", "Kingswood", "Kirrawee", "Kirribilli",
    "Kogarah", "La Perouse", "Lakemba", "Lane Cove", "Lavender Bay",
    "Leichhardt", "Lewisham", "Lidcombe", "Lindfield", "Little Bay",
    "Liverpool", "Longueville", "Lugarno", "Macquarie Park", "Manly",
    "Manly Vale", "Maroubra", "Marsfield", "Mascot", "Matraville",
    "Meadowbank", "Menai", "Merrylands", "Millers Point", "Milsons Point",
    "Miranda", "Moore Park", "Mosman", "Mount Druitt", "Naremburn",
    "Narrabeen", "Narraweena", "Narwee", "Neutral Bay", "Newport",
    "Newtown", "Normanhurst", "North Epping", "North Parramatta", "North Ryde",
    "North Strathfield", "North Sydney", "Northbridge", "Oatley", "Paddington",
    "Padstow", "Pagewood", "Panania", "Parramatta", "Peakhurst",
    "Penrith", "Petersham", "Point Piper", "Potts Point", "Punchbowl",
    "Pymble", "Pyrmont", "Queens Park", "Randwick", "Redfern",
    "Revesby", "Rhodes", "Riverview", "Rockdale", "Rose Bay",
    "Rosebery", "Roseville", "Rouse Hill", "Rozelle", "Rushcutters Bay",
    "Ryde", "Schofields", "Seaforth", "Seven Hills", "Silverwater",
    "St Ives", "St Leonards", "St Peters", "Stanmore", "Strathfield",
    "Summer Hill", "Surry Hills", "Sutherland", "Sydenham", "Sydney",
    "Tamarama", "Taren Point", "Telopea", "Tempe", "The Rocks",
    "Thornleigh", "Toongabbie", "Turramurra", "Ultimo", "Vaucluse",
    "Villawood", "Wahroonga", "Waitara", "Waterloo", "Watsons Bay",
    "Waverley", "Waverton", "Wentworthville", "Westmead", "Wetherill Park",
    "Willoughby", "Windsor", "Wollstonecraft", "Woollahra", "Woolloomooloo",
    "Yagoona", "Zetland"
  ],
  Melbourne: [
    "Abbotsford", "Albert Park", "Alphington", "Altona", "Armadale",
    "Ascot Vale", "Ashburton", "Ashwood", "Balaclava", "Balwyn",
    "Bayswater", "Bentleigh", "Black Rock", "Blackburn", "Boronia",
    "Box Hill", "Brighton", "Brunswick", "Brunswick East", "Brunswick West",
    "Bulleen", "Bundoora", "Camberwell", "Canterbury", "Carnegie",
    "Caulfield", "Chelsea", "Cheltenham", "Coburg", "Coburg North",
    "Collingwood", "Dandenong", "Doncaster", "Doveton", "Elsternwick",
    "Eltham", "Elwood", "Essendon", "Fairfield", "Fitzroy",
    "Fitzroy North", "Footscray", "Forest Hill", "Frankston", "Glen Iris",
    "Glen Waverley", "Glenroy", "Greensborough", "Hawthorn", "Heidelberg",
    "Heidelberg West", "Hoppers Crossing", "Ivanhoe", "Kensington", "Keysborough",
    "Kilsyth", "Knox", "Laverton", "Lilydale", "Lower Plenty",
    "Macleod", "Malvern", "Malvern East", "Maribyrnong", "McKinnon",
    "Mentone", "Mernda", "Middle Park", "Mill Park", "Mitcham",
    "Moonee Ponds", "Moorabbin", "Mooroolbark", "Mornington", "Mount Waverley",
    "Mulgrave", "Niddrie", "Noble Park", "Northcote", "Nunawading",
    "Oakleigh", "Ormond", "Pakenham", "Pascoe Vale", "Point Cook",
    "Port Melbourne", "Prahran", "Preston", "Research", "Richmond",
    "Ringwood", "Rosanna", "Sandringham", "Seaford", "Seddon",
    "South Yarra", "Spotswood", "Springvale", "St Albans", "St Kilda East",
    "Sunshine", "Surrey Hills", "Templestowe", "Thomastown", "Thornbury",
    "Toorak", "Vermont", "Viewbank", "Wantirna", "Werribee",
    "Williamstown", "Windsor", "Wyndham Vale", "Yarraville",
  ],
  Brisbane: [
    "Albion", "Alderley", "Algester", "Annerley", "Anstead",
    "Ascot", "Ashgrove", "Aspley", "Auchenflower", "Balmoral",
    "Banyo", "Bardon", "Birkdale", "Boondall", "Bracken Ridge",
    "Bridgeman Downs", "Brighton", "Bulimba", "Calamvale", "Camp Hill",
    "Cannon Hill", "Capalaba", "Carindale", "Carina", "Cashmere",
    "Chapel Hill", "Chelmer", "Chermside", "Chermside West", "Clayfield",
    "Cleveland", "Cooparoo", "Corinda", "Darra", "Deagon",
    "Dutton Park", "Eagle Farm", "Enoggera", "Everton Hills", "Everton Park",
    "Fairfield", "Ferny Grove", "Fig Tree Pocket", "Fitzgibbon", "Forest Lake",
    "Fortitude Valley", "Gaythorne", "Geebung", "Gordon Park", "Graceville",
    "Grange", "Greenslopes", "Hamilton", "Hawthorne", "Herston",
    "Holland Park", "Holland Park West", "Inala", "Indooroopilly", "Kalinga",
    "Kangaroo Point", "Kedron", "Kelvin Grove", "Kenmore", "Keperra",
    "Lota", "Lutwyche", "Macgregor", "Manly", "Mansfield",
    "McDowall", "Milton", "Mitchelton", "Moorooka", "Mount Gravatt",
    "Mount Gravatt East", "Murarrie", "Nathan", "New Farm", "Newmarket",
    "Nundah", "Oxley", "Paddington", "Pallara", "Parkinson",
    "Petrie Terrace", "Pullenvale", "Red Hill", "Richlands", "Robertson",
    "Rocklea", "Runcorn", "Sandgate", "Shorncliffe", "Stafford",
    "Stafford Heights", "Stretton", "Sunnybank", "Sunnybank Hills", "Taringa",
    "Tarragindi", "Teneriffe", "The Gap", "Tingalpa", "Toowong",
    "Upper Kedron", "Upper Mount Gravatt", "Virginia", "Wavell Heights", "Wilston",
    "Windsor", "Wishart", "Woolloongabba", "Wynnum", "Zillmere",
  ],
  Perth: [
    "Alfred Cove", "Applecross", "Armadale", "Ascot", "Attadale",
    "Atwell", "Balcatta", "Baldivis", "Bayswater", "Beckenham",
    "Bentley", "Beechboro", "Belmont", "Bibra Lake", "Booragoon",
    "Brentwood", "Bull Creek", "Burswood", "Butler", "Canning Vale",
    "Cannington", "Carlisle", "Carramar", "Caversham", "Churchlands",
    "Claremont", "Clarkson", "Cloverdale", "Cockburn Central", "Como",
    "Cottesloe", "Daglish", "Dianella", "Duncraig", "East Fremantle",
    "East Victoria Park", "Eden Hill", "Ellenbrook", "Embleton", "Floreat",
    "Fremantle", "Girrawheen", "Glen Forrest", "Glendalough", "Gosnells",
    "Hamilton Hill", "Hammond Park", "High Wycombe", "Hillarys", "Innaloo",
    "Inglewood", "Joondanna", "Joondalup", "Kalamunda", "Kardinya",
    "Karrinyup", "Kelmscott", "Kenwick", "Kingsley", "Langford",
    "Leederville", "Leeming", "Lynwood", "Maddington", "Marangaroo",
    "Maylands", "Midland", "Mindarie", "Mirrabooka", "Morley",
    "Mount Hawthorn", "Mount Lawley", "Mount Pleasant", "Murdoch", "Myaree",
    "Nollamara", "Noranda", "North Beach", "North Coogee", "North Fremantle",
    "North Perth", "Northbridge", "Osborne Park", "Padbury", "Palmyra",
    "Riverton", "Rivervale", "Rockingham", "Roleystone", "Safety Bay",
    "Scarborough", "Seville Grove", "Shelley", "Sorrento", "Spearwood",
    "Stirling", "Subiaco", "Success", "Thornlie", "Trigg",
    "Tuart Hill", "Tuart Hill", "Victoria Park", "Waikiki", "Wangara",
    "Warnbro", "Warwick", "Watermans Bay", "Wembley", "Wembley Downs",
    "Westminster", "Willeton", "Wilson", "Woodlands", "Woodvale",
    "Wooroloo", "Yangebup",
  ],
  Adelaide: [
    "Aberfoyle Park", "Albert Park", "Aldgate", "Angle Vale", "Ascot Park",
    "Belair", "Bellevue Heights", "Beverley", "Birkenhead", "Blair Athol",
    "Bowden", "Brahma Lodge", "Bridgewater", "Brighton", "Brompton",
    "Burnside", "Christie Downs", "Christies Beach", "Clarence Gardens", "Clarence Park",
    "Colonel Light Gardens", "Crafers", "Craigmore", "Davoren Park", "Dernancourt",
    "Daw Park", "Direk", "Dover Gardens", "Edwardstown", "Elizabeth",
    "Encounter Bay", "Enfield", "Ethelton", "Exeter", "Findon",
    "Flinders Park", "Fulham", "Fullarton", "Gepps Cross", "Glenelg",
    "Glenelg North", "Glenelg South", "Gilles Plains", "Glenunga", "Goodwood",
    "Greenwith", "Hackham", "Hawthorndene", "Hawthorn", "Henley Beach",
    "Hindmarsh", "Hope Valley", "Hove", "Ingle Farm", "Islington",
    "Kensington", "Kensington Gardens", "Klemzig", "Linden Park", "Lockleys",
    "Magill", "Mawson Lakes", "Millswood", "Mitcham", "Modbury",
    "Morphett Vale", "Mount Barker", "Murray Bridge", "Norwood", "Noarlunga Centre",
    "O'Halloran Hill", "Oaklands Park", "Osborne", "Para Hills", "Paradise",
    "Parkside", "Plympton", "Port Adelaide", "Prospect", "Queenstown",
    "Redwood Park", "Reynella", "Ridgehaven", "Rose Park", "Salisbury",
    "Semaphore", "Sefton Park", "Seaton", "Somerton Park", "Springfield",
    "Stirling", "Stonyfell", "Thebarton", "Torrensville", "Tusmore",
    "Unley", "Valley View", "Walkerville", "West Croydon", "West Lakes",
    "Windsor Gardens", "Woodville",
  ],
  Canberra: [
    "Acton", "Ainslie", "Amaroo", "Aranda", "Banks",
    "Barton", "Belconnen", "Bonner", "Bonython", "Braddon",
    "Bruce", "Calwell", "Campbell", "Casey", "Chapman",
    "Charnwood", "Chifley", "Chisholm", "Clare", "Conder",
    "Cook", "Curtin", "Deakin", "Dickson", "Downer",
    "Dunlop", "Duffy", "Evatt", "Fadden", "Farrer",
    "Fisher", "Florey", "Flynn", "Forde", "Forrest",
    "Franklin", "Fraser", "Garran", "Gilmore", "Giralang",
    "Gordon", "Greenway", "Griffith", "Gungahlin", "Hackett",
    "Harrison", "Hawker", "Holder", "Holt", "Hughes",
    "Hume", "Isaacs", "Isabella Plains", "Kaleen", "Kambah",
    "Kingston", "Latham", "Lawson", "Lyneham", "Lyons",
    "Macgregor", "Macquarie", "Manuka", "McKellar", "Melba",
    "Mitchell", "Monash", "Narrabundah", "Ngunnawal", "Nicholls",
    "O'Connor", "O'Malley", "Oxley", "Page", "Palmerston",
    "Pearce", "Phillip", "Reid", "Richardson", "Rivett",
    "Scullin", "Spence", "Stirling", "Taylor", "Theodore",
    "Throsby", "Tuggeranong", "Turner", "Uriarra Village", "Wanniassa",
    "Watson", "Weetangera", "Weston", "Wright",
  ],
  Hobart: [
    "Battery Point", "Bellerive", "Berriedale", "Blackmans Bay", "Bridgewater",
    "Claremont", "Clarendon Vale", "Derwent Park", "Dynnyrne", "East Risdon",
    "Geilston Bay", "Glenorchy", "Goodwood", "Granton", "Howrah",
    "Kingston", "Kingston Beach", "Lauderdale", "Lenah Valley", "Lindisfarne",
    "Lutana", "Margate", "Midway Point", "Moonah", "Mount Nelson",
    "Mount Stuart", "New Norfolk", "New Town", "Newstead", "Newnham",
    "North Hobart", "Old Beach", "Penguin", "Princes Park", "Risdon Vale",
    "Rokeby", "Rosetta", "Rosny", "Rosny Park", "Sandy Bay",
    "Seven Mile Beach", "Sorell", "South Hobart", "Taroona", "Tranmere",
    "Warrane", "West Hobart", "West Moonah", "Williamstown",
  ],
  Darwin: [
    "Alawa", "Anula", "Bayview", "Berrimah", "Buffalo Creek",
    "Casuarina", "Charles Darwin", "Coconut Grove", "Coonawarra", "Cullen Bay",
    "Driver", "Durack", "Fannie Bay", "Farrar", "Gray",
    "Gunn", "Jingili", "Johnston", "Karama", "Knuckey Lagoon",
    "Larrakeyah", "Leanyer", "Lee Point", "Lyons", "Marrara",
    "Millner", "Moil", "Moulden", "Muirhead", "Nakara",
    "Nightcliff", "Parap", "Rapid Creek", "Rosebery", "Stuart Park",
    "The Gardens", "The Narrows", "Tiwi", "Wagaman", "Wanguri",
    "Wulagi", "Woodroffe", "Woolner", "Zuccoli",
  ],
};

export function pickRandomSuburb(city: string): string | null {
  const list = SUBURBS_BY_CITY[city];
  if (!list || list.length === 0) return null;
  return list[Math.floor(Math.random() * list.length)];
}
